### ISSUE TITLE
Convert PCL to PDF error

### ISSUE THREAD

**Issue by npodbutsky** [aspose-pdf/Aspose.PDF-for-Java#43]
Hello.
I've faced a problem with com.aspose.pdf.examples.AsposePdfExamples.DocumentConversion.ConvertPCLToPDFFormat class. The thing is, it fails with NullPointerException on line 12 :
`Exception in thread "main" java.lang.NullPointerException
	at com.aspose.pdf.internal.pcl.util.BaseFontHelper.lI(Unknown Source)
	at com.aspose.pdf.internal.pcl.util.BaseFontHelper.lI(Unknown Source)
	at com.aspose.pdf.internal.l94n.lI.<init>(Unknown Source)
	at com.aspose.pdf.internal.l94n.lt.<init>(Unknown Source)
	at com.aspose.pdf.internal.pcl.composer.lI.lu(Unknown Source)
	at com.aspose.pdf.internal.pcl.composer.lI.<init>(Unknown Source)
	at com.aspose.pdf.l12j.lI(Unknown Source)
	at com.aspose.pdf.l12j.lI(Unknown Source)
	at com.aspose.pdf.ADocument.lI(Unknown Source)
	at com.aspose.pdf.ADocument.<init>(Unknown Source)
	at com.aspose.pdf.Document.<init>(Unknown Source)
	at com.aspose.pdf.examples.AsposePdfExamples.DocumentConversion.ConvertPCLToPDFFormat.main(ConvertPCLToPDFFormat.java:12)
`.
The only thing I changed was the filename in Document constructor (I changed "Document.pcl" to "src/main/resources/com/aspose/pdf/examples/AsposePdf/Conversion/pcltopdf/test.pcl" so that the constructor can find the source). 

Is there a problem with the "test.pcl" file or something else?
Thank you in advance.

**Comment by farhan-raza** [comment]
@npodbutsky 

We are unable to reproduce the issue as the PDF file is generated fine. We have attached generated file for your kind reference. [test1-converted.pdf](https://github.com/aspose-pdf/Aspose.PDF-for-Java/files/3924400/test1-converted.pdf)

PS: I work with Aspose as Developer Evangelist.

**Comment by kashifiqb** [comment]
@npodbutsky,

Were you able to resolve the issue? Let us know if we could of any help to you.

**Comment by npodbutsky** [comment]
Hello @kashifiqb 

Sorry for not reporting status for a long time. My colleagues and I found that the performance of the converter somehow depends on the environment. Namely, the error occurs on MacOS Catalina and Ubuntu 18.0.4/19.0.4. On Windows and MacOS of earlier versions the converter works fine.
Unfortunately, we didn't manage to determine the cause of the error more precisely, so we decided to leave it for now.

I would be grateful if you could test the example in question on any of the systems mentioned above. Maybe that would give some insight on the cause.

**Comment by asadalikhan90** [comment]
@npodbutsky 

The issue can also cause due to the absence of MS Fonts in the macOS. Please try to install MS Fonts and libgdiplus package in the macOS and check again. In case of any issues, please feel free to create a topic in our [official support forum](https://forum.aspose.com/c/pdf).
